# -*- coding: utf-8 -*-
"""Bike_Demand_Ensemble_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nsHI2YDAKHhUsbKo3pEwMyRqxNnpkNzG
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import KFold, cross_val_score, cross_val_predict
from sklearn.ensemble import RandomForestRegressor, BaggingRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

data = pd.read_csv("/content/hour.csv")
data.head()

data.columns

target = "cnt"

features = [
    'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
    'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed'
]

X = data[features]
y = data[target]

kfold = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

models = {
    "RandomForest (Bagging)": RandomForestRegressor(
        n_estimators=200,
        max_depth=15,
        random_state=42,
        n_jobs=-1
    ),

    "Subagging": BaggingRegressor(
        estimator=DecisionTreeRegressor(max_depth=15),
        n_estimators=200,
        max_samples=0.6,
        random_state=42,
        n_jobs=-1
    ),

    "GradientBoosting (Boosting)": GradientBoostingRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=5,
        random_state=42
    )
}

results = []

for name, model in models.items():
    rmse = -cross_val_score(
        model, X, y,
        cv=kfold,
        scoring='neg_root_mean_squared_error'
    )

    mae = -cross_val_score(
        model, X, y,
        cv=kfold,
        scoring='neg_mean_absolute_error'
    )

    results.append({
        "Model": name,
        "RMSE_mean": rmse.mean(),
        "RMSE_std": rmse.std(),
        "MAE_mean": mae.mean(),
        "MAE_std": mae.std()
    })

results_df = pd.DataFrame(results)
results_df

results_df.to_csv("cv_regression_results.csv", index=False)

best_model = models["GradientBoosting (Boosting)"]

best_model.fit(X, y)

predictions = cross_val_predict(
    best_model, X, y, cv=kfold
)

final_predictions = pd.DataFrame({
    "ActualCnt": y,
    "PredictedCnt": predictions
})

final_predictions.head()

final_predictions.to_csv("final_predictions.csv", index=False)

importances = best_model.feature_importances_

feature_importance_df = pd.DataFrame({
    "Feature": features,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

feature_importance_df.head(8)