# -*- coding: utf-8 -*-
"""Gender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3QnZeobm99enFMjGRCZsOpsClBZAt-6
"""

import pandas as pd

test = pd.read_csv('/content/test.csv')

len(test)

submission = pd.DataFrame({
    'PassengerId': test['PassengerId'],
    'Survived': test['Sex'].apply(lambda x: 1 if x == 'female' else 0)
})

submission.columns

len(submission)

submission['Survived'].unique()

submission.to_csv('gender_submission.csv', index=False)

from google.colab import files
files.download('gender_submission.csv')