# -*- coding: utf-8 -*-
"""House_Pricing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VnHSYFgOra8rCxMfmuCq_Kuc0L6f6PqH
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

import xgboost as xgb

train_df = pd.read_csv('/content/train (1).csv')
test_df  = pd.read_csv('/content/test (1).csv')

print(train_df.shape, test_df.shape)

y = train_df['SalePrice']
X = train_df.drop(['SalePrice'], axis=1)

combined = pd.concat([X, test_df], axis=0)

num_cols = combined.select_dtypes(include=['int64', 'float64']).columns
cat_cols = combined.select_dtypes(include=['object']).columns

combined[num_cols] = combined[num_cols].fillna(combined[num_cols].median())
combined[cat_cols] = combined[cat_cols].fillna('None')

label_encoders = {}

for col in cat_cols:
    le = LabelEncoder()
    combined[col] = le.fit_transform(combined[col])
    label_encoders[col] = le

X_final = combined.iloc[:len(X), :]
test_final = combined.iloc[len(X):, :]

X_train, X_valid, y_train, y_valid = train_test_split(
    X_final, y, test_size=0.2, random_state=42
)

xgb_model = xgb.XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='reg:squarederror',
    random_state=42
)

xgb_model.fit(X_train, y_train)

xgb_preds = xgb_model.predict(X_valid)
rmse_xgb = np.sqrt(mean_squared_error(y_valid, xgb_preds))

print("XGBoost RMSE:", rmse_xgb)

xgb_model.fit(X_final, y)
final_predictions = xgb_model.predict(test_final)

submission = pd.read_csv('/content/sample_submission.csv')

submission['SalePrice'] = final_predictions

submission.to_csv('final_submission.csv', index=False)
print("Submission file created!")

from google.colab import files
files.download('final_submission.csv')